ALTER TABLE usuario ADD COLUMN IF NOT EXISTS role VARCHAR(50);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE institucion ALTER COLUMN nombre TYPE VARCHAR(255);
ALTER TABLE institucion ADD COLUMN IF NOT EXISTS limite_productos VARCHAR(1000);