const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  STOCK_VIEW: "stock.view",
  STOCK_EDIT: "stock.edit",
  STOCK_MOVEMENT_CREATE: "stock.movement.create",
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_ROLE_UPDATE: "users.role.update",
  USERS_STATUS_UPDATE: "users.status.update",
  USERS_DELETE: "users.delete",
  // Productos
  PRODUCTOS_VIEW: "productos.view",
  PRODUCTOS_CREATE: "productos.create",
  PRODUCTOS_EDIT: "productos.edit",
  PRODUCTOS_DELETE: "productos.delete",
  // Movimientos
  MOVIMIENTOS_VIEW: "movimientos.view",
  MOVIMIENTOS_CREATE: "movimientos.create",
  // Ajustes
  AJUSTES_VIEW: "ajustes.view",
  AJUSTES_CREATE: "ajustes.create",
  // Auditoría
  AUDITORIA_VIEW: "auditoria.view",
  // Pedidos
  PEDIDOS_VIEW: "pedidos.view",
  PEDIDOS_CREATE: "pedidos.create",
  PEDIDOS_MANAGE: "pedidos.manage",
  // Instituciones
  INSTITUCIONES_VIEW: "instituciones.view",
  INSTITUCIONES_CREATE: "instituciones.create",
  INSTITUCIONES_EDIT: "instituciones.edit",
  INSTITUCIONES_DELETE: "instituciones.delete",
  INSTITUCIONES_ASIGNAR: "instituciones.asignar"
};

const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_EDIT,
    PERMISSIONS.STOCK_MOVEMENT_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_ROLE_UPDATE,
    PERMISSIONS.USERS_STATUS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.PRODUCTOS_VIEW,
    PERMISSIONS.PRODUCTOS_CREATE,
    PERMISSIONS.PRODUCTOS_EDIT,
    PERMISSIONS.PRODUCTOS_DELETE,
    PERMISSIONS.MOVIMIENTOS_VIEW,
    PERMISSIONS.MOVIMIENTOS_CREATE,
    PERMISSIONS.AJUSTES_VIEW,
    PERMISSIONS.AJUSTES_CREATE,
    PERMISSIONS.AUDITORIA_VIEW,
    PERMISSIONS.PEDIDOS_VIEW,
    PERMISSIONS.PEDIDOS_MANAGE,
    PERMISSIONS.INSTITUCIONES_VIEW,
    PERMISSIONS.INSTITUCIONES_CREATE,
    PERMISSIONS.INSTITUCIONES_EDIT,
    PERMISSIONS.INSTITUCIONES_DELETE,
    PERMISSIONS.INSTITUCIONES_ASIGNAR
  ],
  directivo: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCTOS_VIEW,
    PERMISSIONS.PEDIDOS_VIEW,
    PERMISSIONS.PEDIDOS_CREATE,
    PERMISSIONS.AUDITORIA_VIEW
  ],
  operador: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_EDIT,
    PERMISSIONS.STOCK_MOVEMENT_CREATE,
    PERMISSIONS.PRODUCTOS_VIEW,
    PERMISSIONS.PRODUCTOS_CREATE,
    PERMISSIONS.PRODUCTOS_EDIT,
    PERMISSIONS.MOVIMIENTOS_VIEW,
    PERMISSIONS.MOVIMIENTOS_CREATE,
    PERMISSIONS.AJUSTES_VIEW,
    PERMISSIONS.AJUSTES_CREATE,
    PERMISSIONS.AUDITORIA_VIEW
  ],
  consulta: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.PRODUCTOS_VIEW,
    PERMISSIONS.MOVIMIENTOS_VIEW,
    PERMISSIONS.AJUSTES_VIEW,
    PERMISSIONS.AUDITORIA_VIEW
  ]
};

function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

function hasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
  hasPermission
};
